### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [Awesome-Image-Registration-Organization/awesome-image-registration#18]
Hello, I found some broken links:

- [ ] https://github.com/NUAAXQ/awesome-point-cloud-analysis-2022/blob/master/openaccess.thecvf.com/content/ICCV2021/papers/Jubran_Provably_Approximated_Point_Cloud_Registration_ICCV_2021_paper.pdf (file: README.md, status code: 404)
- [ ] https://arpg.colorado.edu/papers/hmrf_icp.pdf (file: README.md, error: EHOSTUNREACH)
- [ ] http://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14751 (file: README.md, status code: 404)
- [ ] http://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14188 (file: README.md, status code: 404)
- [ ] http://empire10.isi.uu.nl/ (file: README.md, error: ENOTFOUND)
- [ ] http://oai.epi-ucsf.org/datarelease/ (file: README.md, error: ENOTFOUND)
- [ ] http://www.escience.cn/people/JunweiHan/NWPU-RESISC45.html (file: README.md, error: ECONNRESET)
- [ ] http://captain.whu.edu.cn/DOTAweb/index.html (file: README.md, error: ECONNRESET)
- [ ] http://staffhome.ecm.uwa.edu.au/~00053650/databases.html (file: README.md, error: ENOTFOUND)
- [ ] http://elastix.isi.uu.nl/ (file: README.md, error: ENOTFOUND)
- [ ] http://elastix.isi.uu.nl/download/elastix_manual_v4.8.pdf (file: README.md, error: ENOTFOUND)
- [ ] http://cvrs.whu.edu.cn/downloads/ebooks/Multiple%20View%20Geometry%20in%20Computer%20Vision%20(Second%20Edition).pdf (file: README.md, status code: 404)
- [ ] http://www.cs.toronto.edu/~kyros/courses/2530/papers/Lecture-14/Szeliski2006.pdf (file: README.md, status code: 404)
- [ ] https://blog.sicara.com/image-registration-sift-deep-learning-3c794d794b7a (file: README.md, error: ERR_TLS_CERT_ALTNAME_INVALID)
- [ ] https://blog.csdn.net/Ha_ku/article/details/797556232 (file: README.md, status code: 404)
- [ ] https://blog.csdn.net/weixin_43236944/article/details/881885323 (file: README.md, status code: 404)
- [ ] https://blog.csdn.net/u014636245/article/details/827559664 (file: README.md, status code: 404)
- [ ] https://www.icra2020.org/ (file: README.md, error: ERR_TLS_CERT_ALTNAME_INVALID)

**Comment by youngfish42** [comment]
Cool~ This validation works great, I'll have to spend some time looking for alternative sources.

By the way, can you tell me how you check for invalid links?

**Comment by ndsvw** [comment]
No problem..

I used https://github.com/tcort/markdown-link-check / https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by Tloops** [comment]
@youngfish42 I'm working on fixing the links today. Please wait for my pull request. 😃

**Comment by youngfish42** [comment]
> @youngfish42 I'm working on fixing the links today. Please wait for my pull request. 😃

thanks a lot!
