### ISSUE TITLE
add some remote sensing image registration?

### ISSUE THREAD

**Issue by Ym1314520** [Awesome-Image-Registration-Organization/awesome-image-registration#20]

**Comment by youngfish42** [comment]
Very good proposal, looking forward to your contribution

**Comment by Ym1314520** [comment]
Thanks for your reply！I have found some paper and code of image registration！If you need I will send to you.



---Original---
From: "Yuwen ***@***.***&gt;
Date: Tue, Apr 30, 2024 20:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re:[Awesome-Image-Registration-Organization/awesome-image-registration] add someremote sensing image registration? (Issue #20)




 
Very good proposal, looking forward to your contribution

**Comment by youngfish42** [comment]
I am updating the literature list from 2022 to present. Finished in about an hour.
You can check it out in an hour and add the paper information that I haven't compiled yet.

Your contribution is welcome, thank you~
