### ISSUE TITLE
Two links of Remote Sensing are not available

### ISSUE THREAD

**Issue by cycyco** [Awesome-Image-Registration-Organization/awesome-image-registration#6]
I can't open the links of NWPU-RESISC45 and DOTA dataset. Do they need to be refreshed?

**Comment by youngfish42** [comment]
The links have became invalid.  

Maybe you can search other web to download them.

For example,  
[NWPU Data Set](https://hyper.ai/datasets/5449) 
[DOTA Data Set](https://hyper.ai/datasets/4920)
